accel_feature: false
accel_penalty: 0
act_coef: 1
act_type: vel_discrete
adv_norm: false
alg: 'TRPO'
av: 1
center_reward: true
circ_feature: false
circumference: 640
circumference_max: 654
circumference_min: 628
collision_penalty: 100
constant_rl_velocity: null
debug: false
device: cpu
disable_amp: true
e: false
gamma: 0.999
global_reward: false
handcraft: 2.5
hc_param: 20
hc_reward: average
horizon: 2000
incorrect_penalty: 0
inexec_penalty: null
initial_space: free
insocial_penalty: null
lc_act_type: continuous
logger: true
low: -1
main: true
max_accel: 0.5
max_decel: 0.5
max_speed: 35
meta_stable_penalty: 0
n_actions: 18
n_lanes: 1
n_steps: 1000
n_veh: 40
name: veldis18-20-TRPO-0
norm_reward: true
opt_level: O0
render: false
res: /home/gridsan/jcho/piecewise-constant-control-jcho/results/230419-jcho-ring640/veldis18-20-TRPO-0
rl_sigma: 0.0
sigma: 0.2
sim_step: 0.1
skip_stat_steps: 2000
step_save: 5
tb: true
tmp: false
warmup_steps: 1000
wb: false

